{{- $fullName := include "simple-crud.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "simple-crud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-crud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-crud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: simple-crud-app
        image: aartman/simple-crud
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: "/app/appsettings.Staging.json"
          subPath: "appsettings.Staging.json"
      volumes:
      - name: secret-volume
        secret:
          secretName: {{ $fullName }}-secret
          defaultMode: 420