apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-crud.fullname" . }}
spec:
  selector:
    {{- include "simple-crud.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80